export const cities = [
    { nazov: 'Beňadiková', cena: 3},
    { nazov: 'Bobrovček', cena: 3},
    { nazov: 'Bobrovec', cena: 3},
    { nazov: 'Demänovská dolina (Jasná)', cena: 4},
    { nazov: 'Galovany', cena: 3},
    { nazov: 'Gôtovany', cena: 4},
    { nazov: 'Jakubovany', cena: 3},
    { nazov: 'Jalovec', cena: 3},
    { nazov: 'Jamník', cena: 4},
    { nazov: 'Konská', cena: 4},
    { nazov: 'Kvačany', cena: 4},
    { nazov: 'Liptovská Ondrášová', cena: 1},
    { nazov: 'Liptovská Porúbka', cena: 4},
    { nazov: 'Liptovská Sielnica', cena: 4},
    { nazov: 'Liptovské Matiašovce', cena: 4},
    { nazov: 'Liptovský Hrádok', cena: 4},
    { nazov: 'Liptovský Ján', cena: 3},
    { nazov: 'Liptovský Mikuláš', cena: 1},
    { nazov: 'Liptovský Mikuláš - Bodice', cena: 2},
    { nazov: 'Liptovský Mikuláš - časť Podbreziny', cena: 1},
    { nazov: 'Liptovský Mikuláš - Demänová', cena: 2},
    { nazov: 'Liptovský Mikuláš - Tatralandia', cena: 2},
    { nazov: 'Liptovský Ondrej', cena: 3},
    { nazov: 'Liptovský Peter', cena: 4},
    { nazov: 'Liptovský Trnovec', cena: 3},
    { nazov: 'Ľubeľa', cena: 4},
    { nazov: 'Okoličné', cena: 1},
    { nazov: 'Partizánska Ľupča', cena: 4},
    { nazov: 'Pavčina Lehota', cena: 3},
    { nazov: 'Pavlova Ves', cena: 3},
    { nazov: 'Ploštín / Iľanovo', cena: 2},
    { nazov: 'Podtureň', cena: 3},
    { nazov: 'Smrečany', cena: 3},
    { nazov: 'Svätý kríž', cena: 3},
    { nazov: 'Trstené', cena: 3},
    { nazov: 'Uhorská Ves', cena: 3},
    { nazov: 'Vavrišovo', cena: 4},
    { nazov: 'Závažná poruba', cena: 3},
    { nazov: 'Žiar', cena: 3},
]